[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "20"

[deploy]
startCommand = "npx ts-node src/index.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }